### ISSUE TITLE
Screen flashes with noise during boot

### ISSUE THREAD

**Issue by dagwoodland** [pimoroni/picosystem#9]
When booting with `disable_startup_logo(<project_name>)` in CMakeLists.txt the screen briefly flashes with RGB noise during boot. This does not happen if `disable_startup_logo(<project_name>)` is omitted.

**Comment by Gadgetoid** [comment]
That's... interesting. I wonder what the difference is. I wasn't convinced we could get data to the screen quickly enough on startup to clear it before the backlight comes on.

The flash is pretty normal, either way, since the screen has its own internal RAM and it's uninitialised until... it's initialised.

Ha! Okay we have a huge sleep in before the screen is cleared:

https://github.com/pimoroni/picosystem/blob/8e50f8173eb2ee3d67fbbd3acebcbb77911d9192/libraries/picosystem.cpp#L83

**Comment by Fordi** [comment]
I have a draft PR (#24) for this (just removes the delay, which resolves it on hardware\*), but I'm a little confused: Hoisting the `pen(0, 0, 0); clear();` out of the `#ifdef NO_STARTUP_LOGO` (so it hits both branches) does _not_ resolve the issue, even though it should, in theory.

If I then move the `backlight(75);` into its own `#ifdef NO_STARTUP_LOGO` branch _after_ the `sleep(300);`, it also resolves it\*.

I'm going to continue experimenting for a bit before undrafting.

-----
\* though there's still a nigh-imperceptable one-frame flash of randomness.

**Comment by Fordi** [comment]
Hey, can you test with the latest?  I believe the bug's been resolved with the merge of #24.

**Comment by dagwoodland** [comment]
Hi, I am happy to confirm that it is now fixed for me too! I'm not even seeing a "nigh-imperceptable one-frame flash of randomness" in slow-mo footage on my phone.

Thank you for looking into it.
